### ISSUE TITLE
3D CI tests not running; file not found

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#36]
```
 ctest -V -R gemini:hdf5:3d_fang:dryrun
```

Fails with the error:

```
9: Test command: /usr/local/Frameworks/Python.framework/Versions/3.7/bin/python3.7 "/Users/zettergm/Projects/GEMINI/scripts/run_test.py" "3d_fang" "-mpiexec" "/usr/local/bin/mpiexec" "/Users/zettergm/Projects/GEMINI/build/gemini.bin" "/Users/zettergm/Projects/GEMINI/build/test3d_fang" "-dryrun"
9: Test timeout computed to be: 60
9: Traceback (most recent call last):
9:   File "/Users/zettergm/Projects/GEMINI/scripts/run_test.py", line 134, in <module>
9:     dryrun=P.dryrun,
9:   File "/Users/zettergm/Projects/GEMINI/scripts/run_test.py", line 86, in run_test
9:     shutil.copy2(z["dir"] / cfg["indat_size"], input_dir)
9:   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 266, in copy2
9:     copyfile(src, dst, follow_symlinks=follow_symlinks)
9:   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
9:     with open(src, 'rb') as fsrc:
9: FileNotFoundError: [Errno 2] No such file or directory: '/Users/zettergm/Projects/GEMINI/tests/data/test3d_fang/tests/data/test3d_fang/inputs/simsize.h5'
4/4 Test  #9: gemini:hdf5:3d_fang:dryrun .......***Failed    0.35 sec
```

**Comment by mattzett** [comment]
All of the 2D tests run fine.

**Comment by mattzett** [comment]
I can confirm the glow test also has this problem:

```
ctest -V -R gemini:hdf5:3d_glow:dryrun
```

also fails with the same error

**Comment by scivision** [comment]
I think this is fixed. This part of the Python code was reworked a couple months ago and I'm not currently seeing this problem. Please reopen if it's happening still.
