### ISSUE TITLE
Bounds Check: GDI_periodic_lowres

### ISSUE THREAD

**Issue by scivision** [gemini3d/gemini3d#77]
GDI_periodic_lowres fails on bound check with -dryrun, with output below:

```
6/148 Testing: run_bounds_check:GDI_periodic_lowres
6/148 Test: run_bounds_check:GDI_periodic_lowres
Command: "/home/beef/code/gemini3d/build/Debug/gemini3d.run.debug" "/mnt/raid/ci/GDI_periodic_lowres" "-mpiexec" "/usr/lib64/openmpi/bin/mpiexec" "-dryrun"
Directory: /home/beef/code/gemini3d/build/Release
"run_bounds_check:GDI_periodic_lowres" start time: Oct 27 17:21 EDT
Output:
----------------------------------------------------------
gemini3d.run: detected CPU count: 32
MPI partition of lx2, lx3: 184 48 is lid2, lid3: 4 8
MPI images: 32

<snip>

/mnt/raid/ci/GDI_periodic_lowres/inputs/simsize.h5 input dimensions:    34   184    48
Target (output) grid structure dimensions:    34   184    48
Sent ICs to workers in   3.172E-02 seconds.

Initial conditions (root):
------------------------
Min/max input density:   0.00E+00   1.46E+11
Min/max input velocity:  -5.52E+02   2.75E+01
Min/max input temperature:   0.00E+00   1.49E+03
Min/max input electric potential:   0.00E+00   0.00E+00
Min/max input electric potential (full grid):   0.00E+00   0.00E+00
 Priming electric field input
init_Efieldinput: Prime electric field input files: ymd,utsec: 20130220 18000.000
 init_Efieldinput: load next file for electric field input   0.0000000000000000
           0  using Lagrangian grid moving at:     500.00000745058060        0.0000000000000000
 Priming precipitation input
 Computing background and priming neutral perturbation input (if used)
 Initial neutral density and temperature (from MSIS) at time:          2013           2          20   18000.000000000000       calculated in time:     5.5562000000000000E-002
 Initial neutral winds (from HWM) at time:          2013           2          20   18000.000000000000       calculated in time:     2.8360000000000052E-003
Recomputed initial dist. fields:
     gemini    0.0000000000000000        0.0000000000000000
     gemini   -0.0000000000000000       -0.0000000000000000
     gemini    0.0000000000000000        0.0000000000000000
 Recomputed initial BG fields:
        0.0000000000000000        0.0000000000000000
        0.0000000000000000        0.0000000000000000
       -2.5000000372529030E-002  -2.5000000372529030E-002
 Recomputed initial drifts:
       -499.99915044276207       0.12063574780673696
       -249.69821805881347        68.445269778559336
At line 257 of file /home/beef/code/gemini3d/build/src/numerical/calculus/calculus.f90
Fortran runtime error: Dimension 2 of array 'grad2d1_curv_alt_23' has extent 48 instead of 49

Error termination. Backtrace:
#0  0x7fe0586c2171 in ???
#1  0x7fe0586c2d19 in ???
#2  0x7fe0586c30fb in ???
#3  0x97baf0 in __calculus_MOD_grad2d1_curv_alt_23
	at /home/beef/code/gemini3d/build/src/numerical/calculus/calculus.f90:257
#4  0x89a40c in __potential_mumps_MOD_potential2d_polarization_periodic
	at /home/beef/code/gemini3d/src/numerical/potential/potential2d.f90:69
#5  0x80d7e3 in __potential_comm_MOD_potential_root_mpi_curv
	at /home/beef/code/gemini3d/src/numerical/potential/potential_root.f90:172
#6  0x7d7596 in __potential_comm_MOD_electrodynamics_curv
	at /home/beef/code/gemini3d/src/numerical/potential/potential_comm_mumps.f90:221
#7  0x419b86 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:397
#8  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#9  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30087,1],0]
  Exit code:    2
--------------------------------------------------------------------------
[beefy:682987] 31 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[beefy:682987] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
ERROR STOP gemini.bin run failure

Error termination. Backtrace:
#0  0x7fe8e59ab171 in ???
#1  0x7fe8e59abd19 in ???
#2  0x7fe8e59ace8e in ???
#3  0x446be1 in gemini3d_run
	at /home/beef/code/gemini3d/src/utils/gemini3d_run.f90:52
#4  0x446c34 in main
	at /home/beef/code/gemini3d/src/utils/gemini3d_run.f90:5
<end of output>
Test time =   3.07 sec
----------------------------------------------------------
Test Failed.
"run_bounds_check:GDI_periodic_lowres" end time: Oct 27 17:21 EDT
"run_bounds_check:GDI_periodic_lowres" time elapsed: 00:00:03
----------------------------------------------------------
```

**Comment by scivision** [comment]
fixed by 2912b27e80ec2e64fbf581590ae88a84c4091ac7
