### ISSUE TITLE
Bounds Check: KHI_periodic_lowres

### ISSUE THREAD

**Issue by scivision** [gemini3d/gemini3d#78]
Similar to #77 for KHI_periodic_lowres:

output:

```
<snip>

/mnt/raid/ci/KHI_periodic_lowres/inputs/simsize.h5 input dimensions:    34   256   128
Target (output) grid structure dimensions:    34   256   128
Sent ICs to workers in   1.311E-01 seconds.

Initial conditions (root):
------------------------
Min/max input density:   0.00E+00   1.36E+11
Min/max input velocity:  -5.08E+02   2.66E+01
Min/max input temperature:   0.00E+00   1.49E+03
Min/max input electric potential:   8.14E+02   1.92E+04
Min/max input electric potential (full grid):   8.14E+02   3.08E+04
 Priming electric field input
init_Efieldinput: Prime electric field input files: ymd,utsec: 20130220 28500.000
 init_Efieldinput: load next file for electric field input   0.0000000000000000
 Priming precipitation input
 Computing background and priming neutral perturbation input (if used)
 Initial neutral density and temperature (from MSIS) at time:          2013           2          20   28500.000000000000       calculated in time:    0.34272900000000006
 Initial neutral winds (from HWM) at time:          2013           2          20   28500.000000000000       calculated in time:     1.8281999999999909E-002
Recomputed initial dist. fields:
     gemini    0.0000000000000000        0.0000000000000000
     gemini   -7.4999188818411971E-002  -6.4298823712095554E-002
     gemini    0.0000000000000000        0.0000000000000000
 Recomputed initial BG fields:
        0.0000000000000000        0.0000000000000000
        0.0000000000000000        0.0000000000000000
        0.0000000000000000        0.0000000000000000
 Recomputed initial drifts:
       -749.98440813173238        199.99206355270539
       -1499.9837763682397       -2.2945137763304003E-003
At line 257 of file /home/beef/code/gemini3d/build/src/numerical/calculus/calculus.f90
Fortran runtime error: Dimension 2 of array 'grad2d1_curv_alt_23' has extent 128 instead of 129

Error termination. Backtrace:
#0  0x7f15c5d2d171 in ???
#1  0x7f15c5d2dd19 in ???
#2  0x7f15c5d2e0fb in ???
#3  0x97baf0 in __calculus_MOD_grad2d1_curv_alt_23
	at /home/beef/code/gemini3d/build/src/numerical/calculus/calculus.f90:257
#4  0x89a40c in __potential_mumps_MOD_potential2d_polarization_periodic
	at /home/beef/code/gemini3d/src/numerical/potential/potential2d.f90:69
#5  0x80d7e3 in __potential_comm_MOD_potential_root_mpi_curv
	at /home/beef/code/gemini3d/src/numerical/potential/potential_root.f90:172
#6  0x7d7596 in __potential_comm_MOD_electrodynamics_curv
	at /home/beef/code/gemini3d/src/numerical/potential/potential_comm_mumps.f90:221
#7  0x419b86 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:397
#8  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#9  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[29571,1],0]
  Exit code:    2
--------------------------------------------------------------------------
[beefy:683503] 31 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[beefy:683503] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
ERROR STOP gemini.bin run failure

Error termination. Backtrace:
#0  0x7f4d1a272171 in ???
#1  0x7f4d1a272d19 in ???
#2  0x7f4d1a273e8e in ???
#3  0x446be1 in gemini3d_run
	at /home/beef/code/gemini3d/src/utils/gemini3d_run.f90:52
#4  0x446c34 in main
	at /home/beef/code/gemini3d/src/utils/gemini3d_run.f90:5
<end of output>
Test time =   4.56 sec
----------------------------------------------------------
Test Failed.
"run_bounds_check:KHI_periodic_lowres" end time: Oct 27 17:27 EDT
"run_bounds_check:KHI_periodic_lowres" time elapsed: 00:00:04
----------------------------------------------------------
```

**Comment by scivision** [comment]
fixed by 2912b27e80ec2e64fbf581590ae88a84c4091ac7
