### ISSUE TITLE
Bounds Check: Tohoku 3D   tohoku20113D_lowres_3Dneu

### ISSUE THREAD

**Issue by scivision** [gemini3d/gemini3d#79]
error log:

```
135/148 Testing: run_bounds_check:tohoku20113D_lowres_3Dneu
135/148 Test: run_bounds_check:tohoku20113D_lowres_3Dneu
Command: "/home/beef/code/gemini3d/build/Debug/gemini3d.run.debug" "/mnt/raid/ci/tohoku20113D_lowres_3Dneu" "-mpiexec" "/usr/lib64/openmpi/bin/mpiexec" "-dryrun"
Directory: /home/beef/code/gemini3d/build/Release
"run_bounds_check:tohoku20113D_lowres_3Dneu" start time: Oct 27 17:28 EDT
Output:
----------------------------------------------------------
gemini3d.run: detected CPU count: 32
MPI partition of lx2, lx3: 128 48 is lid2, lid3: 4 8
MPI images: 32

<snip>

/mnt/raid/ci/tohoku20113D_lowres_3Dneu/inputs/simsize.h5 input dimensions:   512   128    48
Target (output) grid structure dimensions:   512   128    48
Sent ICs to workers in   2.396E-01 seconds.

Initial conditions (root):
------------------------
Min/max input density:   0.00E+00   1.93E+12
Min/max input velocity:  -2.03E+02   2.09E+02
Min/max input temperature:   0.00E+00   2.31E+03
Min/max input electric potential:   0.00E+00   0.00E+00
Min/max input electric potential (full grid):   0.00E+00   0.00E+00
 Priming electric field input
 Priming precipitation input
 Computing background and priming neutral perturbation input (if used)
 Initial neutral density and temperature (from MSIS) at time:          2011           3          11   35100.000000000000       calculated in time:    0.47727200000000014
 Initial neutral winds (from HWM) at time:          2011           3          11   35100.000000000000       calculated in time:     3.9384000000000086E-002
 !!!Attempting initial load of neutral dynamics files!!! This is a workaround to insure compatibility with restarts...        2011           3          11   35100.000000000000
 Computing alt,radial distance values for plasma grid and completing rotations
 ...Clearing out unit vectors (after projections)...
 Projection checking:    -1.1102230246251565E-016   1.6653345369377348E-016  -1.1102230246251565E-016   1.1102230246251565E-016  0.99999999999999989        1.0000000000000000
READ neutral size from:
/mnt/raid/ci/acoustic3D_cartesian_neutrals
 Neutral data has lx,ly,lz size:            80          90         100  with spacing dx,dy,dz   9375.0000000000000        8333.2999999999993        5000.0000000000000
 ...creating vertical grid and sending to workers...
 Created full neutral grid with y,z extent:  -370312.50000000000        370312.50000000000       -370831.84999999998        370831.84999999998        0.0000000000000000        495000.00000000000
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
 Receiving xn and yn ranges from workers...
 Subgrid extents:             1   0.0000000000000000        495000.00000000000       -296886.87691879936       -193648.41709209242       -522251.07875446643        214613.25994687024
At line 615 of file /home/beef/code/gemini3d/src/neutral/proj.f90
Fortran runtime error: Index '0' of dimension 1 of array 'yitmp' below lower bound of 1

Error termination. Backtrace:
#0  0x7fbd1360d171 in ???
#1  0x7fbd1360dd19 in ???
#2  0x7fbd1360e0fb in ???
#0  0x7f7c1567e171 in ???
#1  0x7f7c1567ed19 in ???
#2  0x7f7c1567f0fb in ???
#0  0x7f899d46d171 in ???
#1  0x7f899d46dd19 in ???
#2  0x7f899d46e0fb in ???
#0  0x7f21a76ef171 in ???
#1  0x7f21a76efd19 in ???
#2  0x7f21a76f00fb in ???
#0  0x7f4b4b532171 in ???
#1  0x7f4b4b532d19 in ???
#2  0x7f4b4b5330fb in ???
#0  0x7f6b16dcc171 in ???
#1  0x7f6b16dccd19 in ???
#2  0x7f6b16dcd0fb in ???
#0  0x7fca902f3171 in ???
#1  0x7fca902f3d19 in ???
#2  0x7fca902f40fb in ???
#0  0x7f486cb4e171 in ???
#1  0x7f486cb4ed19 in ???
#2  0x7f486cb4f0fb in ???
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#0  0x7f90df9c1171 in ???
#1  0x7f90df9c1d19 in ???
#2  0x7f90df9c20fb in ???
#0  0x7f9ee0b2c171 in ???
#1  0x7f9ee0b2cd19 in ???
#2  0x7f9ee0b2d0fb in ???
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#0  0x7faa9aab8171 in ???
#1  0x7faa9aab8d19 in ???
#2  0x7faa9aab90fb in ???
#0  0x7feb86fd9171 in ???
#1  0x7feb86fd9d19 in ???
#2  0x7feb86fda0fb in ???
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#0  0x7f3433fb5171 in ???
#1  0x7f3433fb5d19 in ???
#2  0x7f3433fb60fb in ???
#0  0x7ff0ca10f171 in ???
#1  0x7ff0ca10fd19 in ???
#2  0x7ff0ca1100fb in ???
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#0  0x7fcff6fa2171 in ???
#1  0x7fcff6fa2d19 in ???
#2  0x7fcff6fa30fb in ???
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#0  0x7f9a7591d171 in ???
#1  0x7f9a7591dd19 in ???
#2  0x7f9a7591e0fb in ???
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#3  0x5683f6 in __neutral.proj_MOD_slabrange
	at /home/beef/code/gemini3d/src/neutral/proj.f90:615
#4  0x5791b3 in __neutral.perturb_MOD_gridproj_dneu3d
	at /home/beef/code/gemini3d/src/neutral/proj.f90:509
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#5  0x55b3ea in __neutral.perturb_MOD_neutral_perturb_3d
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:264
#6  0x55f842 in __neutral_MOD_neutral_perturb
	at /home/beef/code/gemini3d/src/neutral/perturb.f90:63
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
#7  0x53c7bf in __neutral_MOD_init_neutrals
	at /home/beef/code/gemini3d/src/neutral/neutral.f90:183
#8  0x412369 in gemini_main
	at /home/beef/code/gemini3d/src/libgemini.f90:312
#9  0x405fe4 in gemini3d_main
	at /home/beef/code/gemini3d/src/gemini_main.f90:55
#10  0x406300 in main
	at /home/beef/code/gemini3d/src/gemini_main.f90:21
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[29154,1],2]
  Exit code:    2
--------------------------------------------------------------------------
[beefy:683918] 31 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[beefy:683918] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
ERROR STOP gemini.bin run failure

Error termination. Backtrace:
#0  0x7f40ce4a9171 in ???
#1  0x7f40ce4a9d19 in ???
#2  0x7f40ce4aae8e in ???
#3  0x446be1 in gemini3d_run
	at /home/beef/code/gemini3d/src/utils/gemini3d_run.f90:52
#4  0x446c34 in main
	at /home/beef/code/gemini3d/src/utils/gemini3d_run.f90:5
<end of output>
Test time =   5.39 sec
----------------------------------------------------------
Test Failed.
"run_bounds_check:tohoku20113D_lowres_3Dneu" end time: Oct 27 17:28 EDT
"run_bounds_check:tohoku20113D_lowres_3Dneu" time elapsed: 00:00:05
----------------------------------------------------------
```

**Comment by mattzett** [comment]
Yep this was fixed in branch inputdata_ESFmods
